### Get data
 GET http://localhost:9000/api/cource HTTP/1.1   

### GET single cource
GET http://localhost:5000/api/cource/620b5c1e6b064d0603cfdf8b HTTP/1.1

### put data
POST http://localhost:2000/api/cource  HTTP/1.1

Content-Type: application/json

{
"Buyer": "mr.mahin mittal",
"Host": "mr.lakshay chopra",
"Amount": "2000",
"Coursetitle": "learn html/css",
"Description": "Duration is of 2.5 ho urs",
"startDate": "20:1:22",
"endDate": "20:1:22",
}

### update data
PUT http://localhost:2000/api/cource/620b5ac1b66da8f24979aff3 HTTP/1.1

Content-Type: application/json  

{
  "Buyer": "mr.raju goyal"
}

### deleate cources
DELETE http://localhost:2000/api/cource/620b5ac1b66da8f24979aff3 HTTP/1.1
